
#ifndef S11N_TD_CPP_H__
#define S11N_TD_CPP_H__

#include <cstdint>
#include <map>
#include <memory>
#include <string>
#include <variant>
#include <vector>
#include <ostream>

#include <typedef/builtin_types.h>

// Generated by the Typedef compiler

#ifndef TD_THROW
#define TD_STRINGIZE_DETAIL(x) #x
#define TD_STRINGIZE(x) TD_STRINGIZE_DETAIL(x)
#define TD_THROW(msg) (throw msg __FILE__ ":" TD_STRINGIZE(__LINE__))
#endif

#ifndef TD_AUTO_ALLOC
#define TD_AUTO_ALLOC 1
#endif

namespace s11n {

// Forward declarations.

// Struct and variant declarations

// Struct and variant JSON declarations


// Tmplate function declarations


} // namespace s11n


#endif  // S11N_TD_CPP_H__
