
#include "json_demo.td.h"

// Generated by the Typedef compiler (EXPERIMENTAL)

#include <string>
#include <sstream>
#include <locale>
#include <codecvt>
#include <iomanip>
// JSON parser required headers
#include "rapidjson/document.h"
#include <charconv>
#include <iomanip>
#include <locale>
// JSON writer required headers
#include <charconv>
#include <iomanip>
#include <locale>


namespace {

std::string escape_char32_t_as_literal(char32_t c) {
  switch (c) {
    case U'\a':
      return R"(U'\a')";
    case U'\b':
      return R"(U'\b')";
    case U'\f':
      return R"(U'\f')";
    case U'\n':
      return R"(U'\n')";
    case U'\r':
      return R"(U'\r')";
    case U'\t':
      return R"(U'\t')";
    case U'\v':
      return R"(U'\v')";
    case U'\'':
      return R"(U'\'')";
    case U'\"':
      return R"(U'\"')";
    case U'\\':
      return R"(U'\\')";
    default:
      if (c < 32 || c >= 0x7F) {
        // For characters outside of the ASCII range
        std::ostringstream oss;
        oss << "U'\\U" << std::setw(8) << std::setfill('0') << std::hex
            << std::uppercase << static_cast<int>(c) << "'";
        return oss.str();
      } else {
        // For all other characters, return as is
        return "U'" + std::string(1, static_cast<char>(c)) + "'";
      }
  }
}

template <typename T>
inline bool IsEmpty(const std::vector<T>& v) {
  return v.size() == 0;
}


inline std::string escape_json(const std::string& s) {
  std::ostringstream o;
  for (auto c = s.cbegin(); c != s.cend(); c++) {
    switch (*c) {
      case '"': o << "\\\""; break;
      case '\\': o << "\\\\"; break;
      case '\b': o << "\\b"; break;
      case '\f': o << "\\f"; break;
      case '\n': o << "\\n"; break;
      case '\r': o << "\\r"; break;
      case '\t': o << "\\t"; break;
      default:
        if ('\x00' <= *c && *c <= '\x1f') {
          o << "\\u" << std::hex << std::setw(4) << std::setfill('0')
            << static_cast<int>(*c);
        } else {
          o << *c;
        }
    }
  }
  return o.str();
}

inline std::string char32ToJsonString(char32_t c) {
  std::wstring_convert<std::codecvt_utf8<char32_t>, char32_t> converter;
  std::string utf8 = converter.to_bytes(&c, &c + 1);
  return escape_json(utf8);
}

// This is a very inefficint way of doing this, but
// C++17 standard libs don't give us great options.
// TODO: Also it may not work in C++20?
std::u32string decode_utf8(const std::string& utf8_string) {
  struct destructible_codecvt : public std::codecvt<char32_t, char, std::mbstate_t> {
    using std::codecvt<char32_t, char, std::mbstate_t>::codecvt;
    ~destructible_codecvt() = default;
  };
  std::wstring_convert<destructible_codecvt, char32_t> utf32_converter;
  return utf32_converter.from_bytes(utf8_string);
}

inline char32_t GetCharValue(std::string_view str) {
  if (str.size() == 2 && str[0] == '\\') {
    switch (str[1]) {
      case 'n':
        return U'\n';
      case 'r':
        return U'\r';
      case 't':
        return U'\t';
      case '\\':
        return U'\\';
      case '0':
        return U'\0';
      case '\'':
        return U'\'';
      case '\"':
        return U'\"';
    }
  }
  if (str.size() == 4 && str[0] == '\\' && str[1] == 'x') {
    // TODO this seems rather inefficient, do something better?
    std::istringstream ss(std::string(str.substr(2)));
    int value;
    ss >> std::hex >> value;
    return static_cast<char32_t>(value);
  }

  if (str.size() >= 3 && str.size() <= 10 && str[0] == '\\' && str[1] == 'u' &&
      str[2] == '{' && str.back() == '}') {
    // TODO this seems rather inefficient, do something better?
    std::istringstream ss(std::string(str.substr(3, str.size() - 4)));
    int value;
    ss >> std::hex >> value;
    return static_cast<char32_t>(value);
  }

  if (str.size() > 0) {
    std::string inner_str(str);
    std::u32string str32 = decode_utf8(inner_str);
    if (str32.size() == 1) {
      return str32[0];
    }
  }
  throw std::runtime_error("JSON format error: expected 'char'.");
}


bool JsonParseBool(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (val.IsBool()) {
    return val.GetBool();
  } else {
    throw std::runtime_error("JSON format error: expected 'bool'.");
  }
}
char32_t JsonParseChar(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (val.IsString()) {
    std::string str(val.GetString(), val.GetStringLength());
    return GetCharValue(str);
  } else {
    throw std::runtime_error("JSON format error: expected 'string'.");
  }
}
std::string JsonParseStr(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (val.IsString()) {
    return val.GetString();
  } else {
    throw std::runtime_error("JSON format error: expected 'string'.");
  }
}
float JsonParseF32(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (val.IsDouble()) {
    return (float)val.GetDouble();
  } else {
    throw std::runtime_error("JSON format error: expected 'float'.");
  }
}
double JsonParseF64(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (val.IsDouble()) {
    return val.GetDouble();
  } else {
    throw std::runtime_error("JSON format error: expected 'double'.");
  }
}
std::uint8_t JsonParseU8(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (val.IsUint()) {
    unsigned int ui = val.GetUint();
    if (ui > std::numeric_limits<std::uint8_t>::max() ||
        ui < std::numeric_limits<std::uint8_t>::min()) {
      throw std::runtime_error("JSON format error: unsigned integer '" +
                               std::to_string(ui) +
                               "' exceeded 'u8' capacity.");
    }
    return (std::uint8_t)ui;
  } else {
    throw std::runtime_error("JSON format error: expected 'unsigned integer'.");
  }
}
std::uint16_t JsonParseU16(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (val.IsUint()) {
    unsigned int ui = val.GetUint();
    if (ui > std::numeric_limits<std::uint16_t>::max() ||
        ui < std::numeric_limits<std::uint16_t>::min()) {
      throw std::runtime_error("JSON format error: unsigned integer '" +
                               std::to_string(ui) +
                               "' exceeded 'u16' capacity.");
    }
    return (std::uint16_t)ui;
  } else {
    throw std::runtime_error("JSON format error: expected 'unsigned integer'.");
  }
}
std::uint32_t JsonParseU32(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (val.IsUint()) {
    return val.GetUint();
  } else {
    throw std::runtime_error("JSON format error: expected 'unsigned integer'.");
  }
}
std::uint64_t JsonParseU64(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (val.IsUint64()) {
    return val.GetUint64();
  } else {
    throw std::runtime_error("JSON format error: expected 'unsigned integer'.");
  }
}
std::int8_t JsonParseI8(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (val.IsInt()) {
    int ui = val.GetInt();
    if (ui > std::numeric_limits<std::int8_t>::max() ||
        ui < std::numeric_limits<std::int8_t>::min()) {
      throw std::runtime_error("JSON format error: integer '" +
                               std::to_string(ui) +
                               "' exceeded 'i8' capacity.");
    }
    return (std::int8_t)ui;
  } else {
    throw std::runtime_error("JSON format error: expected 'integer'.");
  }
}
std::int16_t JsonParseI16(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (val.IsInt()) {
    int ui = val.GetInt();
    if (ui > std::numeric_limits<std::int16_t>::max() ||
        ui < std::numeric_limits<std::int16_t>::min()) {
      throw std::runtime_error("JSON format error: integer '" +
                               std::to_string(ui) +
                               "' exceeded 'i16' capacity.");
    }
    return (std::int16_t)ui;
  } else {
    throw std::runtime_error("JSON format error: expected 'integer'.");
  }
}
std::int32_t JsonParseI32(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (val.IsInt()) {
    return val.GetInt();
  } else {
    throw std::runtime_error("JSON format error: expected 'integer'.");
  }
}
std::int64_t JsonParseI64(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (val.IsInt64()) {
    return val.GetInt64();
  } else {
    throw std::runtime_error("JSON format error: expected 'integer'.");
  }
}
template <typename T>
T GetIntFromString(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (!val.IsString()) {
    throw std::runtime_error("JSON format error: expected 'string'.");
  }
  std::string digits = val.GetString();
  std::string_view digits_view(digits);
  T value{};
  auto result = std::from_chars(digits_view.begin(), digits_view.end(), value);
  bool ended_early = result.ptr != digits_view.end();
  if (result.ec == std::errc() && !ended_early) {
    return value;
  } else if (result.ec == std::errc::invalid_argument) {
    throw std::runtime_error(
        "JSON format error: expected string encoded integer.");
  } else if (result.ec == std::errc::result_out_of_range) {
    throw std::runtime_error("JSON format error: number out of range.");
  } else {
    throw std::runtime_error(
        "JSON format error: expected string encoded integer.");
  }
}
bool GetBoolFromString(const rapidjson::GenericValue<rapidjson::UTF8<>>& val) {
  if (!val.IsString()) {
    throw std::runtime_error("JSON format error: expected 'string'.");
  }
  std::string maybe_bool_str = val.GetString();
  if (maybe_bool_str == "true") {
    return true;
  } else if (maybe_bool_str == "false") {
    return false;
  } else {
    throw std::runtime_error(
        "JSON format error: expected string encoded bool 'true' or 'false'.");
  }
}

// Struct and variant JSON forward declarations

json_demo::StructA JsonParseStructA(const rapidjson::Value& obj);

json_demo::StructA::NestedStruct JsonParseStructA_NestedStruct(const rapidjson::Value& obj);

json_demo::StructA::NestedVariant JsonParseStructA_NestedVariant(const rapidjson::Value& obj);

json_demo::StructA::inline_structT JsonParseStructA_inline_structT(const rapidjson::Value& obj);

json_demo::StructA::inline_variantT JsonParseStructA_inline_variantT(const rapidjson::Value& obj);

json_demo::StructB JsonParseStructB(const rapidjson::Value& obj);

json_demo::StructB::NestedStruct JsonParseStructB_NestedStruct(const rapidjson::Value& obj);

json_demo::StructC JsonParseStructC(const rapidjson::Value& obj);

json_demo::StructC::NestedStruct JsonParseStructC_NestedStruct(const rapidjson::Value& obj);

json_demo::VariantA JsonParseVariantA(const rapidjson::Value& obj);

// Struct and variant JSON definitions

json_demo::StructA JsonParseStructA(const rapidjson::Value& val) {
  if (!val.IsObject()) {
    throw std::runtime_error("JSON format error: expected 'object'.");
  }
  json_demo::StructA ret;
  {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_bool");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_bool() = JsonParseBool(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_char");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_char() = JsonParseChar(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_str");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_str() = JsonParseStr(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_f32");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_f32() = JsonParseF32(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_f64");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_f64() = JsonParseF64(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_u8");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_u8() = JsonParseU8(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_u16");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_u16() = JsonParseU16(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_u32");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_u32() = JsonParseU32(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_u64");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_u64() = JsonParseU64(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_i8");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_i8() = JsonParseI8(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_i16");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_i16() = JsonParseI16(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_i32");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_i32() = JsonParseI32(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_i64");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_i64() = JsonParseI64(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("nested_struct");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsObject()) {
      ret.nested_struct() = JsonParseStructA_NestedStruct(val);
    } else {
      throw std::runtime_error("JSON format error: expected 'object'.");
    }
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("inline_struct");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsObject()) {
      ret.inline_struct() = JsonParseStructA_inline_structT(val);
    } else {
      throw std::runtime_error("JSON format error: expected 'object'.");
    }
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("nested_variant");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsObject()) {
      if (val.MemberCount() > 1) {
        throw std::runtime_error("JSON format error: one member expected for variant type; found " + std::to_string(val.MemberCount()));
      }
      ret.nested_variant() = JsonParseStructA_NestedVariant(val);
    } else {
      throw std::runtime_error("JSON format error: expected 'object'.");
    }
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("inline_variant");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsObject()) {
      if (val.MemberCount() > 1) {
        throw std::runtime_error("JSON format error: one member expected for variant type; found " + std::to_string(val.MemberCount()));
      }
      ret.inline_variant() = JsonParseStructA_inline_variantT(val);
    } else {
      throw std::runtime_error("JSON format error: expected 'object'.");
    }
  }
  } 
  return ret;
}

json_demo::StructA::NestedStruct JsonParseStructA_NestedStruct(const rapidjson::Value& val) {
  if (!val.IsObject()) {
    throw std::runtime_error("JSON format error: expected 'object'.");
  }
  json_demo::StructA::NestedStruct ret;
  {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("a");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.a() = JsonParseI32(val);
  }
  } 
  return ret;
}


json_demo::StructA::NestedVariant JsonParseStructA_NestedVariant(const rapidjson::Value& val) {
  if (!val.IsObject()) {
    throw std::runtime_error("JSON format error: expected 'object'.");
  }
  json_demo::StructA::NestedVariant ret;
  {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("c");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.c() = JsonParseI32(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("d");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.d() = JsonParseStr(val);
  }
  } 
  return ret;
}


json_demo::StructA::inline_structT JsonParseStructA_inline_structT(const rapidjson::Value& val) {
  if (!val.IsObject()) {
    throw std::runtime_error("JSON format error: expected 'object'.");
  }
  json_demo::StructA::inline_structT ret;
  {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("b");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.b() = JsonParseStr(val);
  }
  } 
  return ret;
}


json_demo::StructA::inline_variantT JsonParseStructA_inline_variantT(const rapidjson::Value& val) {
  if (!val.IsObject()) {
    throw std::runtime_error("JSON format error: expected 'object'.");
  }
  json_demo::StructA::inline_variantT ret;
  {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("e");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.e() = JsonParseI32(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("f");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.f() = JsonParseStr(val);
  }
  } 
  return ret;
}



json_demo::StructB JsonParseStructB(const rapidjson::Value& val) {
  if (!val.IsObject()) {
    throw std::runtime_error("JSON format error: expected 'object'.");
  }
  json_demo::StructB ret;
  {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_vec_bool");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsArray()) {
      
auto json_parse_array_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using VectorType = std::remove_reference_t<decltype(value_type)>;
  VectorType vec;
  for (rapidjson::SizeType ii = 0; ii < src.Size(); ii++) {
    vec.push_back(JsonParseBool(src[ii]));
  }
  return vec;
};

      ret.example_vec_bool() = json_parse_array_lambda(ret.example_vec_bool(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'array'.");
    }
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_vec_char");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsArray()) {
      
auto json_parse_array_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using VectorType = std::remove_reference_t<decltype(value_type)>;
  VectorType vec;
  for (rapidjson::SizeType ii = 0; ii < src.Size(); ii++) {
    vec.push_back(JsonParseChar(src[ii]));
  }
  return vec;
};

      ret.example_vec_char() = json_parse_array_lambda(ret.example_vec_char(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'array'.");
    }
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_vec_str");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsArray()) {
      
auto json_parse_array_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using VectorType = std::remove_reference_t<decltype(value_type)>;
  VectorType vec;
  for (rapidjson::SizeType ii = 0; ii < src.Size(); ii++) {
    vec.push_back(JsonParseStr(src[ii]));
  }
  return vec;
};

      ret.example_vec_str() = json_parse_array_lambda(ret.example_vec_str(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'array'.");
    }
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_vec_int");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsArray()) {
      
auto json_parse_array_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using VectorType = std::remove_reference_t<decltype(value_type)>;
  VectorType vec;
  for (rapidjson::SizeType ii = 0; ii < src.Size(); ii++) {
    vec.push_back(JsonParseI32(src[ii]));
  }
  return vec;
};

      ret.example_vec_int() = json_parse_array_lambda(ret.example_vec_int(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'array'.");
    }
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_vec_nested_struct");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsArray()) {
      
auto json_parse_array_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using VectorType = std::remove_reference_t<decltype(value_type)>;
  VectorType vec;
  for (rapidjson::SizeType ii = 0; ii < src.Size(); ii++) {
    
      vec.push_back(JsonParseStructB_NestedStruct(src[ii]));
    
  }
  return vec;
};

      ret.example_vec_nested_struct() = json_parse_array_lambda(ret.example_vec_nested_struct(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'array'.");
    }
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_vec_vec_int");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsArray()) {
      
auto json_parse_array_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using VectorType = std::remove_reference_t<decltype(value_type)>;
  VectorType vec;
  for (rapidjson::SizeType ii = 0; ii < src.Size(); ii++) {
    
    if (src.IsArray()) {
      vec.emplace_back();
      auto& innerVec = vec.back();
      
auto json_parse_array_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using VectorType = std::remove_reference_t<decltype(value_type)>;
  VectorType vec;
  for (rapidjson::SizeType ii = 0; ii < src.Size(); ii++) {
    vec.push_back(JsonParseI32(src[ii]));
  }
  return vec;
};

      innerVec = json_parse_array_lambda(innerVec, src[ii]);
    }
  }
  return vec;
};

      ret.example_vec_vec_int() = json_parse_array_lambda(ret.example_vec_vec_int(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'array'.");
    }
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_vec_map_str_int");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsArray()) {
      
auto json_parse_array_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using VectorType = std::remove_reference_t<decltype(value_type)>;
  VectorType vec;
  for (rapidjson::SizeType ii = 0; ii < src.Size(); ii++) {
    
  }
  return vec;
};

      ret.example_vec_map_str_int() = json_parse_array_lambda(ret.example_vec_map_str_int(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'array'.");
    }
  }
  } 
  return ret;
}

json_demo::StructB::NestedStruct JsonParseStructB_NestedStruct(const rapidjson::Value& val) {
  if (!val.IsObject()) {
    throw std::runtime_error("JSON format error: expected 'object'.");
  }
  json_demo::StructB::NestedStruct ret;
  {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("a");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.a() = JsonParseI32(val);
  }
  } 
  return ret;
}



json_demo::StructC JsonParseStructC(const rapidjson::Value& val) {
  if (!val.IsObject()) {
    throw std::runtime_error("JSON format error: expected 'object'.");
  }
  json_demo::StructC ret;
  {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_map_bool_bool");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsObject()) {
      
auto json_parse_map_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using MapType = std::remove_reference_t<decltype(value_type)>;
  MapType map;
  using KeyType = typename MapType::key_type;
  using ValType = typename MapType::mapped_type;
  using PairType = std::pair<const KeyType, ValType>;
  for (auto& m : src.GetObject()) {
    KeyType key = GetBoolFromString(m.name);

    ValType map_val = JsonParseBool(m.value);

    map.emplace(std::make_pair(key, std::move(map_val)));
  }
  return map;
};

      ret.example_map_bool_bool() = json_parse_map_lambda(ret.example_map_bool_bool(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'object'.");
    }
    
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_map_char_char");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsObject()) {
      
auto json_parse_map_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using MapType = std::remove_reference_t<decltype(value_type)>;
  MapType map;
  using KeyType = typename MapType::key_type;
  using ValType = typename MapType::mapped_type;
  using PairType = std::pair<const KeyType, ValType>;
  for (auto& m : src.GetObject()) {
    KeyType key = JsonParseChar(m.name);

    ValType map_val = JsonParseChar(m.value);

    map.emplace(std::make_pair(key, std::move(map_val)));
  }
  return map;
};

      ret.example_map_char_char() = json_parse_map_lambda(ret.example_map_char_char(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'object'.");
    }
    
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_map_str_str");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsObject()) {
      
auto json_parse_map_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using MapType = std::remove_reference_t<decltype(value_type)>;
  MapType map;
  using KeyType = typename MapType::key_type;
  using ValType = typename MapType::mapped_type;
  using PairType = std::pair<const KeyType, ValType>;
  for (auto& m : src.GetObject()) {
    KeyType key = JsonParseStr(m.name);

    ValType map_val = JsonParseStr(m.value);

    map.emplace(std::make_pair(key, std::move(map_val)));
  }
  return map;
};

      ret.example_map_str_str() = json_parse_map_lambda(ret.example_map_str_str(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'object'.");
    }
    
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_map_int_int");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsObject()) {
      
auto json_parse_map_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using MapType = std::remove_reference_t<decltype(value_type)>;
  MapType map;
  using KeyType = typename MapType::key_type;
  using ValType = typename MapType::mapped_type;
  using PairType = std::pair<const KeyType, ValType>;
  for (auto& m : src.GetObject()) {
    KeyType key = GetIntFromString<std::int32_t>(m.name);

    ValType map_val = JsonParseI32(m.value);

    map.emplace(std::make_pair(key, std::move(map_val)));
  }
  return map;
};

      ret.example_map_int_int() = json_parse_map_lambda(ret.example_map_int_int(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'object'.");
    }
    
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_map_str_nested_struct");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsObject()) {
      
auto json_parse_map_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using MapType = std::remove_reference_t<decltype(value_type)>;
  MapType map;
  using KeyType = typename MapType::key_type;
  using ValType = typename MapType::mapped_type;
  using PairType = std::pair<const KeyType, ValType>;
  for (auto& m : src.GetObject()) {
    KeyType key = JsonParseStr(m.name);

    
    ValType map_val;
    if (m.value.IsObject()) {
      map_val = JsonParseStructC_NestedStruct(m.value);
    } else {
      throw std::runtime_error("JSON format error: expected 'object'.");
    }

    map.emplace(std::make_pair(key, std::move(map_val)));
  }
  return map;
};

      ret.example_map_str_nested_struct() = json_parse_map_lambda(ret.example_map_str_nested_struct(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'object'.");
    }
    
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_map_str_vec");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsObject()) {
      
auto json_parse_map_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using MapType = std::remove_reference_t<decltype(value_type)>;
  MapType map;
  using KeyType = typename MapType::key_type;
  using ValType = typename MapType::mapped_type;
  using PairType = std::pair<const KeyType, ValType>;
  for (auto& m : src.GetObject()) {
    KeyType key = JsonParseStr(m.name);

    
    ValType map_val;
    if (m.value.IsArray()) {
      
auto json_parse_array_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using VectorType = std::remove_reference_t<decltype(value_type)>;
  VectorType vec;
  for (rapidjson::SizeType ii = 0; ii < src.Size(); ii++) {
    vec.push_back(JsonParseI32(src[ii]));
  }
  return vec;
};

      map_val = json_parse_array_lambda(map_val, m.value);
    } else {
      throw std::runtime_error("JSON format error: expected 'array'.");
    }

    map.emplace(std::make_pair(key, std::move(map_val)));
  }
  return map;
};

      ret.example_map_str_vec() = json_parse_map_lambda(ret.example_map_str_vec(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'object'.");
    }
    
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_map_str_map");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    
    if (val.IsObject()) {
      
auto json_parse_map_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using MapType = std::remove_reference_t<decltype(value_type)>;
  MapType map;
  using KeyType = typename MapType::key_type;
  using ValType = typename MapType::mapped_type;
  using PairType = std::pair<const KeyType, ValType>;
  for (auto& m : src.GetObject()) {
    KeyType key = JsonParseStr(m.name);

    
    ValType map_val;
    if (m.value.IsObject()) {
      
auto json_parse_map_lambda = [](auto& value_type, const rapidjson::Value& src) {
  using MapType = std::remove_reference_t<decltype(value_type)>;
  MapType map;
  using KeyType = typename MapType::key_type;
  using ValType = typename MapType::mapped_type;
  using PairType = std::pair<const KeyType, ValType>;
  for (auto& m : src.GetObject()) {
    KeyType key = JsonParseStr(m.name);

    ValType map_val = JsonParseI32(m.value);

    map.emplace(std::make_pair(key, std::move(map_val)));
  }
  return map;
};

      map_val = json_parse_map_lambda(map_val, m.value);
    } else {
      throw std::runtime_error("JSON format error: expected 'object'.");
    }

    map.emplace(std::make_pair(key, std::move(map_val)));
  }
  return map;
};

      ret.example_map_str_map() = json_parse_map_lambda(ret.example_map_str_map(), val);
    } else {
      throw std::runtime_error("JSON format error: expected 'object'.");
    }
    
  }
  } 
  return ret;
}

json_demo::StructC::NestedStruct JsonParseStructC_NestedStruct(const rapidjson::Value& val) {
  if (!val.IsObject()) {
    throw std::runtime_error("JSON format error: expected 'object'.");
  }
  json_demo::StructC::NestedStruct ret;
  {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("a");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.a() = JsonParseI32(val);
  }
  } 
  return ret;
}



json_demo::VariantA JsonParseVariantA(const rapidjson::Value& val) {
  if (!val.IsObject()) {
    throw std::runtime_error("JSON format error: expected 'object'.");
  }
  json_demo::VariantA ret;
  {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_bool");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_bool() = JsonParseBool(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_char");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_char() = JsonParseChar(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_str");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_str() = JsonParseStr(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_f32");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_f32() = JsonParseF32(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_f64");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_f64() = JsonParseF64(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_u8");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_u8() = JsonParseU8(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_u16");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_u16() = JsonParseU16(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_u32");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_u32() = JsonParseU32(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_u64");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_u64() = JsonParseU64(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_i8");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_i8() = JsonParseI8(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_i16");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_i16() = JsonParseI16(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_i32");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_i32() = JsonParseI32(val);
  }
  } {
  auto obj = val.GetObject();
  rapidjson::Value::ConstMemberIterator iter = obj.FindMember("example_i64");
  if (iter != obj.MemberEnd()) {
    auto& val = iter->value;
    ret.example_i64() = JsonParseI64(val);
  }
  } 
  return ret;
}


}

namespace json_demo {

// Struct and variant definitions

// StructA member definitions

// StructB member definitions

// StructC member definitions

// json_demo::VariantA member definitions

// Struct and variant JSON declarations

std::string ToJson(const StructA& from) {
  std::stringstream ss;
  ToJson(ss, from);
  return ss.str();
}
void ToJson(std::ostream& os, const StructA& from) {
  os << "{";
  
os << "\"example_bool\":"; os << (from.example_bool() ? "true" : "false");
os << ",";
os << "\"example_char\":"; os << "\"" << char32ToJsonString(from.example_char()) << "\"";
os << ",";
os << "\"example_str\":"; os << "\"" << escape_json(from.example_str()) << "\"";
os << ",";
os << "\"example_f32\":"; os << from.example_f32();
os << ",";
os << "\"example_f64\":"; os << from.example_f64();
os << ",";
os << "\"example_u8\":"; os << (int)from.example_u8();
os << ",";
os << "\"example_u16\":"; os << from.example_u16();
os << ",";
os << "\"example_u32\":"; os << from.example_u32();
os << ",";
os << "\"example_u64\":"; os << from.example_u64();
os << ",";
os << "\"example_i8\":"; os << (int)from.example_i8();
os << ",";
os << "\"example_i16\":"; os << from.example_i16();
os << ",";
os << "\"example_i32\":"; os << from.example_i32();
os << ",";
os << "\"example_i64\":"; os << from.example_i64();
os << ",";
if (from.has_nested_struct()) {os << "\"nested_struct\":"; ToJson(os, from.nested_struct());} else {os << "\"nested_struct\":"; os << "null";}
os << ",";
if (from.has_inline_struct()) {os << "\"inline_struct\":"; ToJson(os, from.inline_struct());} else {os << "\"inline_struct\":"; os << "null";}
os << ",";
if (from.has_nested_variant()) {os << "\"nested_variant\":"; ToJson(os, from.nested_variant());} else {os << "\"nested_variant\":"; os << "null";}
os << ",";
if (from.has_inline_variant()) {os << "\"inline_variant\":"; ToJson(os, from.inline_variant());} else {os << "\"inline_variant\":"; os << "null";}

  os << "}";
}

StructA StructA::FromJson(const std::string& str) {
  rapidjson::Document doc;
  doc.Parse(str.c_str());
  return JsonParseStructA(doc);
}

std::string ToJson(const StructA::NestedStruct& from) {
  std::stringstream ss;
  ToJson(ss, from);
  return ss.str();
}
void ToJson(std::ostream& os, const StructA::NestedStruct& from) {
  os << "{";
  
os << "\"a\":"; os << from.a();

  os << "}";
}

StructA::NestedStruct StructA::NestedStruct::FromJson(const std::string& str) {
  rapidjson::Document doc;
  doc.Parse(str.c_str());
  return JsonParseStructA_NestedStruct(doc);
}


std::string ToJson(const StructA::NestedVariant& from) {
  std::stringstream ss;
  ToJson(ss, from);
  return ss.str();
}
void ToJson(std::ostream& os, const StructA::NestedVariant& from) {
  os << "{";
  
  if (from.is_c()) {
    
os << "\"c\":"; os << from.c();

  }
  
  if (from.is_d()) {
    
os << "\"d\":"; os << "\"" << escape_json(from.d()) << "\"";

  }
  
  os << "}";
}


StructA::NestedVariant StructA::NestedVariant::FromJson(const std::string& str) {
  rapidjson::Document doc;
  doc.Parse(str.c_str());
  return JsonParseStructA_NestedVariant(doc);
}



std::string ToJson(const StructA::inline_structT& from) {
  std::stringstream ss;
  ToJson(ss, from);
  return ss.str();
}
void ToJson(std::ostream& os, const StructA::inline_structT& from) {
  os << "{";
  
os << "\"b\":"; os << "\"" << escape_json(from.b()) << "\"";

  os << "}";
}

StructA::inline_structT StructA::inline_structT::FromJson(const std::string& str) {
  rapidjson::Document doc;
  doc.Parse(str.c_str());
  return JsonParseStructA_inline_structT(doc);
}


std::string ToJson(const StructA::inline_variantT& from) {
  std::stringstream ss;
  ToJson(ss, from);
  return ss.str();
}
void ToJson(std::ostream& os, const StructA::inline_variantT& from) {
  os << "{";
  
  if (from.is_e()) {
    
os << "\"e\":"; os << from.e();

  }
  
  if (from.is_f()) {
    
os << "\"f\":"; os << "\"" << escape_json(from.f()) << "\"";

  }
  
  os << "}";
}


StructA::inline_variantT StructA::inline_variantT::FromJson(const std::string& str) {
  rapidjson::Document doc;
  doc.Parse(str.c_str());
  return JsonParseStructA_inline_variantT(doc);
}


std::string ToJson(const StructB& from) {
  std::stringstream ss;
  ToJson(ss, from);
  return ss.str();
}
void ToJson(std::ostream& os, const StructB& from) {
  os << "{";
  
os << "\"example_vec_bool\":";
{
  auto& arr = from.example_vec_bool();
  
os << "[";
for (size_t ii = 0; ii < arr.size(); ii++) {
  const auto& val = arr[ii];
  os << (val ? "true" : "false");
  if (ii < arr.size() - 1) { os << ","; }
}
os << "]";

}
os << ",";
os << "\"example_vec_char\":";
{
  auto& arr = from.example_vec_char();
  
os << "[";
for (size_t ii = 0; ii < arr.size(); ii++) {
  const auto& val = arr[ii];
  os << "\"" << char32ToJsonString(val) << "\"";
  if (ii < arr.size() - 1) { os << ","; }
}
os << "]";

}
os << ",";
os << "\"example_vec_str\":";
{
  auto& arr = from.example_vec_str();
  
os << "[";
for (size_t ii = 0; ii < arr.size(); ii++) {
  const auto& val = arr[ii];
  os << "\"" << escape_json(val) << "\"";
  if (ii < arr.size() - 1) { os << ","; }
}
os << "]";

}
os << ",";
os << "\"example_vec_int\":";
{
  auto& arr = from.example_vec_int();
  
os << "[";
for (size_t ii = 0; ii < arr.size(); ii++) {
  const auto& val = arr[ii];
  os << val;
  if (ii < arr.size() - 1) { os << ","; }
}
os << "]";

}
os << ",";
os << "\"example_vec_nested_struct\":";
{
  auto& arr = from.example_vec_nested_struct();
  
os << "[";
for (size_t ii = 0; ii < arr.size(); ii++) {
  const auto& val = arr[ii];
  ToJson(os, val);
  if (ii < arr.size() - 1) { os << ","; }
}
os << "]";

}
os << ",";
os << "\"example_vec_vec_int\":";
{
  auto& arr = from.example_vec_vec_int();
  
os << "[";
for (size_t ii = 0; ii < arr.size(); ii++) {
  const auto& val = arr[ii];
  {
    auto& arr = val;
    
os << "[";
for (size_t ii = 0; ii < arr.size(); ii++) {
  const auto& val = arr[ii];
  os << val;
  if (ii < arr.size() - 1) { os << ","; }
}
os << "]";

  }
  if (ii < arr.size() - 1) { os << ","; }
}
os << "]";

}
os << ",";
os << "\"example_vec_map_str_int\":";
{
  auto& arr = from.example_vec_map_str_int();
  
os << "[";
for (size_t ii = 0; ii < arr.size(); ii++) {
  const auto& val = arr[ii];
  {
    auto& map = val;
    
os << "{";
auto iter = map.begin();
while (iter != map.end()) {
  {
  const auto& key = iter->first;
  os << "\"" << escape_json(key) << "\"";
  }
  os << ":";
  {
  const auto& val = iter->second;
  os << val;
  }
  ++iter;
  if (iter != map.end()) { os << ","; }
}
os << "}";

  }
  if (ii < arr.size() - 1) { os << ","; }
}
os << "]";

}

  os << "}";
}

StructB StructB::FromJson(const std::string& str) {
  rapidjson::Document doc;
  doc.Parse(str.c_str());
  return JsonParseStructB(doc);
}

std::string ToJson(const StructB::NestedStruct& from) {
  std::stringstream ss;
  ToJson(ss, from);
  return ss.str();
}
void ToJson(std::ostream& os, const StructB::NestedStruct& from) {
  os << "{";
  
os << "\"a\":"; os << from.a();

  os << "}";
}

StructB::NestedStruct StructB::NestedStruct::FromJson(const std::string& str) {
  rapidjson::Document doc;
  doc.Parse(str.c_str());
  return JsonParseStructB_NestedStruct(doc);
}



std::string ToJson(const StructC& from) {
  std::stringstream ss;
  ToJson(ss, from);
  return ss.str();
}
void ToJson(std::ostream& os, const StructC& from) {
  os << "{";
  
os << "\"example_map_bool_bool\":";
{
  auto& map = from.example_map_bool_bool();
  
os << "{";
auto iter = map.begin();
while (iter != map.end()) {
  {
  const auto& key = iter->first;
  os << (key ? "\"true\"" : "\"false\"");
  }
  os << ":";
  {
  const auto& val = iter->second;
  os << (val ? "true" : "false");
  }
  ++iter;
  if (iter != map.end()) { os << ","; }
}
os << "}";

}
os << ",";
os << "\"example_map_char_char\":";
{
  auto& map = from.example_map_char_char();
  
os << "{";
auto iter = map.begin();
while (iter != map.end()) {
  {
  const auto& key = iter->first;
  os << "\"" << char32ToJsonString(key) << "\"";
  }
  os << ":";
  {
  const auto& val = iter->second;
  os << "\"" << char32ToJsonString(val) << "\"";
  }
  ++iter;
  if (iter != map.end()) { os << ","; }
}
os << "}";

}
os << ",";
os << "\"example_map_str_str\":";
{
  auto& map = from.example_map_str_str();
  
os << "{";
auto iter = map.begin();
while (iter != map.end()) {
  {
  const auto& key = iter->first;
  os << "\"" << escape_json(key) << "\"";
  }
  os << ":";
  {
  const auto& val = iter->second;
  os << "\"" << escape_json(val) << "\"";
  }
  ++iter;
  if (iter != map.end()) { os << ","; }
}
os << "}";

}
os << ",";
os << "\"example_map_int_int\":";
{
  auto& map = from.example_map_int_int();
  
os << "{";
auto iter = map.begin();
while (iter != map.end()) {
  {
  const auto& key = iter->first;
  os << "\"" << std::to_string(key) << "\"";
  }
  os << ":";
  {
  const auto& val = iter->second;
  os << val;
  }
  ++iter;
  if (iter != map.end()) { os << ","; }
}
os << "}";

}
os << ",";
os << "\"example_map_str_nested_struct\":";
{
  auto& map = from.example_map_str_nested_struct();
  
os << "{";
auto iter = map.begin();
while (iter != map.end()) {
  {
  const auto& key = iter->first;
  os << "\"" << escape_json(key) << "\"";
  }
  os << ":";
  {
  const auto& val = iter->second;
  ToJson(os, val);
  }
  ++iter;
  if (iter != map.end()) { os << ","; }
}
os << "}";

}
os << ",";
os << "\"example_map_str_vec\":";
{
  auto& map = from.example_map_str_vec();
  
os << "{";
auto iter = map.begin();
while (iter != map.end()) {
  {
  const auto& key = iter->first;
  os << "\"" << escape_json(key) << "\"";
  }
  os << ":";
  {
  const auto& val = iter->second;
  {
    auto& arr = val;
    
os << "[";
for (size_t ii = 0; ii < arr.size(); ii++) {
  const auto& val = arr[ii];
  os << val;
  if (ii < arr.size() - 1) { os << ","; }
}
os << "]";

  }
  }
  ++iter;
  if (iter != map.end()) { os << ","; }
}
os << "}";

}
os << ",";
os << "\"example_map_str_map\":";
{
  auto& map = from.example_map_str_map();
  
os << "{";
auto iter = map.begin();
while (iter != map.end()) {
  {
  const auto& key = iter->first;
  os << "\"" << escape_json(key) << "\"";
  }
  os << ":";
  {
  const auto& val = iter->second;
  {
    auto& map = val;
    
os << "{";
auto iter = map.begin();
while (iter != map.end()) {
  {
  const auto& key = iter->first;
  os << "\"" << escape_json(key) << "\"";
  }
  os << ":";
  {
  const auto& val = iter->second;
  os << val;
  }
  ++iter;
  if (iter != map.end()) { os << ","; }
}
os << "}";

  }
  }
  ++iter;
  if (iter != map.end()) { os << ","; }
}
os << "}";

}

  os << "}";
}

StructC StructC::FromJson(const std::string& str) {
  rapidjson::Document doc;
  doc.Parse(str.c_str());
  return JsonParseStructC(doc);
}

std::string ToJson(const StructC::NestedStruct& from) {
  std::stringstream ss;
  ToJson(ss, from);
  return ss.str();
}
void ToJson(std::ostream& os, const StructC::NestedStruct& from) {
  os << "{";
  
os << "\"a\":"; os << from.a();

  os << "}";
}

StructC::NestedStruct StructC::NestedStruct::FromJson(const std::string& str) {
  rapidjson::Document doc;
  doc.Parse(str.c_str());
  return JsonParseStructC_NestedStruct(doc);
}



std::string ToJson(const VariantA& from) {
  std::stringstream ss;
  ToJson(ss, from);
  return ss.str();
}
void ToJson(std::ostream& os, const VariantA& from) {
  os << "{";
  
  if (from.is_example_bool()) {
    
os << "\"example_bool\":"; os << (from.example_bool() ? "true" : "false");

  }
  
  if (from.is_example_char()) {
    
os << "\"example_char\":"; os << "\"" << char32ToJsonString(from.example_char()) << "\"";

  }
  
  if (from.is_example_str()) {
    
os << "\"example_str\":"; os << "\"" << escape_json(from.example_str()) << "\"";

  }
  
  if (from.is_example_f32()) {
    
os << "\"example_f32\":"; os << from.example_f32();

  }
  
  if (from.is_example_f64()) {
    
os << "\"example_f64\":"; os << from.example_f64();

  }
  
  if (from.is_example_u8()) {
    
os << "\"example_u8\":"; os << (int)from.example_u8();

  }
  
  if (from.is_example_u16()) {
    
os << "\"example_u16\":"; os << from.example_u16();

  }
  
  if (from.is_example_u32()) {
    
os << "\"example_u32\":"; os << from.example_u32();

  }
  
  if (from.is_example_u64()) {
    
os << "\"example_u64\":"; os << from.example_u64();

  }
  
  if (from.is_example_i8()) {
    
os << "\"example_i8\":"; os << (int)from.example_i8();

  }
  
  if (from.is_example_i16()) {
    
os << "\"example_i16\":"; os << from.example_i16();

  }
  
  if (from.is_example_i32()) {
    
os << "\"example_i32\":"; os << from.example_i32();

  }
  
  if (from.is_example_i64()) {
    
os << "\"example_i64\":"; os << from.example_i64();

  }
  
  os << "}";
}


VariantA VariantA::FromJson(const std::string& str) {
  rapidjson::Document doc;
  doc.Parse(str.c_str());
  return JsonParseVariantA(doc);
}


// Tmplate function definitions


} // namespace json_demo

